### ISSUE TITLE
The html does not show the documentation inside functions

### ISSUE THREAD

**Issue by fran-pena** [romanvm/sphinx_tutorial#1]
Hi,

I've just want to say thank you for your fantastic example of how to use Sphinx. Your example really explains aspects that are not well covered by the official documentation (since Sphinx is for documentation, isn't it ironic?)

I'd also want you to ask what I can be ding wrong, because I don't get the same result than you:
1) I Download and unzip your project.
2) I run in docs/ `sphinx-build.exe -M html . _modules`
The output is
```
Running Sphinx v3.1.1
loading pickled environment... done
[autosummary] generating autosummary for: _autosummary\foo.rst, index.rst, modules.rst, page.rst
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 4 source files that are out of date
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
preparing documents... done
writing output... [100%] page
generating indices...  genindex py-modindexdone
writing additional pages...  searchdone
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.
```
3) The resulting html does not show the documentation inside functions, [see attached image](https://ibb.co/pdDY7Kt).

I would be grateful if you could give some hints.

**Comment by romanvm** [comment]
Yes, looks like autosummary behavior has been changed in recent Sphinx versions. I need to check this.

**Comment by fran-pena** [comment]
I have solved the problem applying [this solution](https://stackoverflow.com/a/21665947/2145428). Basically, creating *_templates/autosummary/module.rst*.

**Comment by romanvm** [comment]
It seems that autodoc now needs explicit `:members:` directives to generate documentation from docstrings, and auto-generated autosummary files do not have such directives. It can be solved by putting default autodoc directives into `conf.py`:
```python
autodoc_default_options = {
    'members': True,
    'show-inheritance': True,
}
```
UPD: it replaces the deprecated `autodoc_default_flags` property.

I will update this project accordingly.
